name: kg-parser
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - device-selector==0.1.0
      - transformers>=4.28.0
      - torch>=1.13.0
      - openai==1.61.1
      - requests
      - tqdm
